### ISSUE TITLE
策略的CONFIG 文件不支持 passphrase  参数

### ISSUE THREAD

**Issue by redkiller79** [coinrust/crex#20]
无法使用OKEX的进行交易 总是提示 result: status=400, message=400 Bad Request, body={"error_message":"OK-ACCESS-PASSPHRASE header is required","code":30004,"error_code":"30004","message":"OK-ACCESS-PASSPHRASE header is required"}
2020/10/03 15:08:05 Http error(400~500) result: status=400, message=400 Bad Request, body={"error_message":"OK-ACCESS-PASSPHRASE header is required","code":30004,"error_code":"30004","message":"OK-ACCESS-PASSPHRASE header is required"}
2020/10/03 15:08:05 Http error(400~500) result: status=400, message=400 Bad Request, body={"error_message":"OK-ACCESS-PASSPHRASE header is required","code":30004,"error_code":"30004","message":"OK-ACCESS-PASSPHRASE header is required"}

**Comment by frankrap** [comment]
OKEx配置中需要添加: passphrase。参考代码:
ex := exchanges.NewExchange(exchanges.OkexFutures,
		//ApiProxyURLOption("socks5://127.0.0.1:1080"), // 使用代理
		ApiAccessKeyOption("[accessKey]"),
		ApiSecretKeyOption("[secretKey]"),
		ApiPassPhraseOption("[passphrase]"), // 注意这个参数,OKEx需要指定此参数
		ApiWebSocketOption(true)) // 开启 WebSocket

**Comment by redkiller79** [comment]
在策略gambler-short的目录下的config.toml 里添加了PassPhrase 设置 任然提示这个错误

**Comment by redkiller79** [comment]
crex-master/serve 下的server.go 里也缺少 PassPhrase  参数

**Comment by redkiller79** [comment]
如果是直接在策略gambler-short的main.go里添加 你说的代码应该怎么添加 请教一下

**Comment by frankrap** [comment]
参考serve.go代码:
https://github.com/coinrust/crex/blob/master/serve/serve.go
请更新最新版本crex v1.2.11，已经支持passphrase参数。

**Comment by redkiller79** [comment]
我更新试试，希望和您多交流下量化策略





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: frankrap <notifications@github.com&gt;
发送时间: 2020年10月3日 17:12
收件人: coinrust/crex <crex@noreply.github.com&gt;
抄送: redkiller79 <655174@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[coinrust/crex] 策略的CONFIG 文件不支持 passphrase  参数 (#20)





 
参考serve.go代码:
 https://github.com/coinrust/crex/blob/master/serve/serve.go
 请更新最新版本crex v1.2.11，已经支持passphrase参数。

**Comment by redkiller79** [comment]
已经跟新了SERVE.GO的文件 并且在gambler-short下的填写了对应信息
[[exchange]]
name = "okexswap"
access_key = "xx-1b73-421a-b1ef-7f6228dd8153"
secret_key = "0CxxB4CA68B47C79BD47994A01E4497"
passphrase = "Ioffxxx5767"
testnet = false
websocket = true

[log]
path = "./app.log"
level = "debug"

[option]
currency = "USDT"             # 货币 BTC
symbol = "LTC-USDT-SWAP"            # 标 BTCUSD
stop_win = 100               # 止盈 500
stop_loss = 100              # 止损 500
first_amount = 1.0           # 单次下单量 1
max_gear = 2.0              # 加倍赌的次数 8
运行gambler-short下的main.go文件还是错误提示

Http error(400~500) result: status=400, message=400 Bad Request, body={"error_message":"Contract does not exist","code":35001,"error_code":"35001","message":"Contract does not exist"}
2020/10/03 19:17:21 Http error(400~500) result: status=400, message=400 Bad Request, body={"error_message":"Contract does not exist","code":35001,"error_code":"35001","message":"Contract does not exist"}
2020/10/03 19:17:21 Http error(400~500) result: status=400, message=400 Bad Request, body={"error_message":"Contract does not exist","code":35001,"error_code":"35001","message":"Contract does not exist"}

**Comment by redkiller79** [comment]
2020/10/03 19:23:09 Currency: USDT
2020/10/03 19:23:09 Symbol: ETH-USDT-SWAP
2020/10/03 19:23:09 {"event":"login","success":true}
Http error(400~500) result: status=400, message=400 Bad Request, body={"error_message":"Contract does not exist","code":35001,"error_code":"35001","message":"Contract does not exist"}
2020/10/03 19:23:09 Http error(400~500) result: status=400, message=400 Bad Request, body={"error_message":"Contract does not exist","code":35001,"error_code":"35001","message":"Contract does not exist"}
2020/10/03 19:23:09 Http error(400~500) result: status=400, message=400 Bad Request, body={"error_message":"Contract does not exist","code":35001,"error_code":"35001","message":"Contract does not exist"}
好像不支持OKEX的永久合约

**Comment by redkiller79** [comment]
我把gambler-shortx下的配置i文件里的币种和标题换成任何都是提示 
2020/10/03 19:48:25 Http error(400~500) result: status=400, message=400 Bad Request, body={"error_message":"Contract does not exist","code":35001,"error_code":"35001","message":"Contract does not exist"}
2020/10/03 19:48:25 Http error(400~500) result: status=400, message=400 Bad Request, body={"error_message":"Contract does not exist","code":35001,"error_code":"35001","message":"Contract does not exist"}

 [option]
currency = "BTC"             # 货币 BTC
symbol = "BTCUSD"            # 标 BTCUSD

**Comment by redkiller79** [comment]
https://github.com/frankrap/huobi-api/hbdm 已经无法引用

**Comment by frankrap** [comment]
应该可以引用，浏览器访问需要访问：
https://github.com/frankrap/huobi-api/tree/master/hbdm
go程序中可以直接引用 github.com/frankrap/huobi-api/hbdm

**Comment by redkiller79** [comment]
都调试成功了，但是策略总在okex的永续合约提示价格有问题无法下单，火币的永续合约提示杠杆为空



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: frankrap <notifications@github.com&gt;
发送时间: 2020年10月4日 09:22
收件人: coinrust/crex <crex@noreply.github.com&gt;
抄送: redkiller79 <655174@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[coinrust/crex] 策略的CONFIG 文件不支持 passphrase  参数 (#20)
