### ISSUE TITLE
[BinanceFuture] upgrade to v2 version, OCO orders, TestNet, WebSockets

### ISSUE THREAD

**Issue by ksidenko** [coinrust/crex#36]
Hi!

I'm pleased that I found your framework! It's great!  

It will be useful if you can update BinaceFuture to https://github.com/adshao/go-binance/v2  version, therу are some reason:
1. Support OCO orders: https://github.com/adshao/go-binance/search?q=oco
2. Support TestNet

Also, there are no WebSockets in this exchange, but it will be handy!
Can you also support it?

**Comment by beaquant** [comment]
thanks for your remind, it upgrade.
welcome pr
