### ISSUE TITLE
suggest: handler with continue will better in csvdataloader

### ISSUE THREAD

**Issue by beaquant** [coinrust/crex#4]
using continue will be better when the return value ok is false
such as, when the data format error in one line, but the next many line is good, after return ok is false, dataloader break. it'll lost many data

https://github.com/coinrust/crex/blob/d53c6e55d62c264cc63e42d04422c3e5ddee10d9/data/csv_dataloader.go#L42

```
		if !ok || tick == nil {
			continue
		}
```

**Comment by frankrap** [comment]
Fixed. Thanks for replying and thanks for sharing this.
