### ISSUE TITLE
Will you upgrade to okex API V5?

### ISSUE THREAD

**Issue by soyoeml** [coinrust/crex#40]
Hi,

This project is amazing. Will you upgrade to okex API V5? V3 doesn't work anymore.

Thanks
-soyoeml

**Comment by beaquant** [comment]
will be, but not suggest using v5, it's high risk

**Comment by kkzhang** [comment]
> will be, but not suggest using v5, it's high risk

why high risk? v3 is deprecated now.

**Comment by f0cii** [comment]
Thank you for your interest in the project! Unfortunately, this project is no longer being maintained, and we will not be updating to new versions or adding new features, including upgrading to okex API V5. We appreciate your understanding.
