### ISSUE TITLE
在SetupStrategyFromConfig()中，为什么不调用ApiProxyURLOption()来配置代理？

### ISSUE THREAD

**Issue by fish2016** [coinrust/crex#44]
在SetupStrategyFromConfig()中，为什么不调用ApiProxyURLOption()来配置代理？ 可以加上去吗？要不我提一个pull request？

ApiProxyURLOption("socks5://127.0.0.1:1080"), // 使用代理

![image](https://user-images.githubusercontent.com/18462875/146682270-eeffc22a-3fa8-4c5e-a221-50f8379c5f09.png)

**Comment by beaquant** [comment]
welcome pr
